
dense: True
timestep: 0.1
variables:
  - name: boat_speed
    type: float
    location: obs
    identifier: speed_idx
specifications:
  - name: R2_test
    spec: always(boat_speed <= 2.1)
    weight: 1.0
